### ISSUE TITLE
The requested module 'attr-accept/dist/es/index.js' does not provide an export named 'default'

### ISSUE THREAD

**Issue by konsumer** [soorria/solid-dropzone#3]
<img width="853" alt="Screenshot 2023-05-17 at 6 09 54 PM" src="https://github.com/soorria/solid-dropzone/assets/83857/60617d19-64d5-45c2-9937-ce5260736b64">

Node: v20.0.0
solid-js: 1.7.5
@soorria/solid-dropzone: 0.0.5

**Comment by soorria** [comment]
What package manager did you use? i.e. `npm`, `yarn`, `pnpm`, etc.

**Comment by konsumer** [comment]
npm.

**Comment by edemaine** [comment]
I'm having the same issue.  I think the issue is that `attr-accept/dist/es/index.js` uses `exports` instead of `export`:

```js
"use strict";

exports.__esModule = true;

exports.default = function (file, acceptedFiles) {
  ...
};
```

I guess it's needs to be `require`d instead (or the bug should be reported upstream).

Update: I can get it working by adding `import 'attr-accept'` in my own source file.  So maybe it's also a Vite issue. (This is in dev mode, using NPM.)

**Comment by edemaine** [comment]
I looked into this more, and there's extensive discussion here: https://github.com/vitejs/vite/issues/3024

I haven't tested yet, but it looks like the current workaround is to modify the config as described here: https://vitejs.dev/guide/dep-pre-bundling.html#the-why
Unfortunately I imagine this has to be done by the user; there's nothing the library can do. ☹️ 

I think the library-level workaround is to use `require` (via [`createRequire`](https://nodejs.org/api/module.html#modulecreaterequirefilename)) until attr-accept offers an ESM build... Or as it's a small dependency we could fork attr-accept and offer our own ESM build.

**Comment by soorria** [comment]
Thanks for all the help! I did a little tinkering locally, and it seems like the only viable fix is updating the ESM build downstream. I tried `createRequire`, but since it's a node built-in, it gets mocked in the browser :(.

**Comment by edemaine** [comment]
Thanks for looking into this!

I've made https://github.com/react-dropzone/attr-accept/pull/64 to provide ESM upstream; hopefully it will get approved (and I got it right) and this issue can be fixed the clean way!

**Comment by AzrizHaziq** [comment]
in case anyone is using `solid-start` i've update the `vite.config.ts` to this and no more error raised

```ts
   ...
  optimizeDeps: {
    include: ['@soorria/solid-dropzone'],
  },

**Comment by soorria** [comment]
Finally found the time, so this should be fixed now since I've vendored the `attr-accept` package. Downside is, if another package is also using `attr-accept`, or you import from it directly, it'll be doubled up in the bundle :cry:.
